<a href="https://colab.research.google.com/github/theAkhileshRai/DeepLearning/blob/master/AssetLvl_Pred_lNN_BinaryClassifierDCP03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

from numpy import loadtxt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler,OneHotEncoder    


from sklearn.metrics import confusion_matrix, classification_report

from keras.utils import to_categorical

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv('/content/DCP_leak_classification_train_data.csv',index_col=False)

In [5]:
df.head()

Unnamed: 0  Unnamed: 0.1  ...            Asset  Binary
0           0             0  ...  Ashland_Unit256     0.0
1           1             1  ...  Ashland_Unit256     0.0
2           2             2  ...  Ashland_Unit256     0.0
3           3             3  ...  Ashland_Unit256     0.0
4           4             4  ...  Ashland_Unit256     0.0

[5 rows x 16 columns]

In [4]:
# df['s_temp_mean*s_pressure_mean'] = df['s_pressure_mean']*df['s_temp_mean']
# df['d_temp_mean*d_pressure_mean'] = df['d_pressure_mean']*df['d_temp_mean']

In [5]:
# df['s_temp_crank*s_pressure_crank'] = df['s_temp_crank']*df['s_pressure_crank']
# df['d_temp_crank*d_pressure_crank'] = df['d_pressure_crank']*df['d_temp_crank']

In [6]:
df.head()

Unnamed: 0  Unnamed: 0.1  ...            Asset  Binary
0           0             0  ...  Ashland_Unit256     0.0
1           1             1  ...  Ashland_Unit256     0.0
2           2             2  ...  Ashland_Unit256     0.0
3           3             3  ...  Ashland_Unit256     0.0
4           4             4  ...  Ashland_Unit256     0.0

[5 rows x 16 columns]

In [7]:
# df1 = pd.read_csv('/content/old_normalised_assets-2.csv',index_col=False)
# df2 = pd.read_csv('/content/new_normalised_assets-2.csv',index_col=False)

In [8]:
# 'Clark county_6', 'RJ booster_1', 'Strawberry_3.csv'

In [19]:
df['Asset'].unique()   

array(['Ashland_Unit256', 'Center station_C2', 'Crossbar_Unit1',
       'El Dorado_Unit', 'Goliad_Unit1100', 'HobitLP_Unit102',
       'Hobit_Unit2', 'Katy_Unit1116', 'Katy_Unit1117', 'LOHT_North',
       'La Porte_K11A', 'Lightning_Unit2 (2)(1).csv', 'RJ_Unit1(1).csv',
       'Lightning_Unit4', 'Reagon_Unit3', 'Saltlake_K71010B',
       'Strawberry_Unit1', 'Reagon_Unit6', 'West Turkey_Unit2'],
      dtype=object)

In [24]:
df2 = df.loc[(df.Asset == 'Clark county_6') | (df.Asset == 'La Porte_K11A') |\
             (df.Asset == 'Strawberry_Unit1') | (df.Asset == 'RJ booster_1') | (df.Asset == 'El Dorado_Unit') | (df.Asset == 'LOHT_North')]

In [25]:
df2.shape

(13656, 16)

In [26]:
df2["Binary"].unique()

array([0., 1.])

In [44]:
df['Asset'].unique()    

array(['Ashland_Unit256', 'Center station_C2', 'Crossbar_Unit1',
       'El Dorado_Unit', 'Goliad_Unit1100', 'HobitLP_Unit102',
       'Hobit_Unit2', 'Katy_Unit1116', 'Katy_Unit1117', 'LOHT_North',
       'La Porte_K11A', 'Lightning_Unit2 (2)(1).csv', 'RJ_Unit1(1).csv',
       'Lightning_Unit4', 'Reagon_Unit3', 'Saltlake_K71010B',
       'Strawberry_Unit1', 'Reagon_Unit6', 'West Turkey_Unit2'],
      dtype=object)

In [30]:
len(df['Asset'].unique() )

19

In [31]:
len(df2['Asset'].unique() )

4

In [ ]:
# 'Clark county_6') | ('La Porte_K11A') |\
#              ('Strawberry_Unit1') | ('RJ booster_1') | ('El Dorado_Unit'

In [47]:
df1 = df.loc[(df.Asset == 'West Turkey_Unit2') | (df.Asset == 'Crossbar_Unit1') | (df.Asset == 'Reagon_Unit6') | (df.Asset == 'Reagon_Unit3') | (df.Asset == 'Hobit_Unit2')|(df.Asset == 'Katy_Unit1116') | (df.Asset == 'Katy_Unit1117') | (df.Asset == 'HobitLP_Unit102') | (df.Asset == 'Goliad_Unit1100') | (df.Asset == 'Lightning_Unit4') | (df.Asset == 'Ashland_Unit256') | (df.Asset == 'Center station_C2') | (df.Asset == 'El Dorado_Unit J2502') | (df.Asset == 'Saltlake_K71010B') | (df.Asset == 'Lightning_Unit2 (2)(1).csv') |  (df.Asset == 'RJ_Unit1(1).csv')]

In [48]:
df1['Asset'].unique()

array(['Ashland_Unit256', 'Center station_C2', 'Crossbar_Unit1',
       'Goliad_Unit1100', 'HobitLP_Unit102', 'Hobit_Unit2',
       'Katy_Unit1116', 'Katy_Unit1117', 'Lightning_Unit2 (2)(1).csv',
       'RJ_Unit1(1).csv', 'Lightning_Unit4', 'Reagon_Unit3',
       'Saltlake_K71010B', 'Reagon_Unit6', 'West Turkey_Unit2'],
      dtype=object)

In [49]:
len(df1['Asset'].unique() )

15

In [50]:
df1.head()

Unnamed: 0  Unnamed: 0.1  ...            Asset  Binary
0           0             0  ...  Ashland_Unit256     0.0
1           1             1  ...  Ashland_Unit256     0.0
2           2             2  ...  Ashland_Unit256     0.0
3           3             3  ...  Ashland_Unit256     0.0
4           4             4  ...  Ashland_Unit256     0.0

[5 rows x 16 columns]

In [51]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'time', 'cyl', 's_temp_crank',
       'd_temp_crank', 's_pressure_crank', 'd_pressure_crank', 'rpm_crank',
       's_temp_mean', 'd_temp_mean', 's_pressure_mean', 'd_pressure_mean',
       'rpm_mean', 'Asset', 'Binary'],
      dtype='object')

In [72]:
df1['Binary'] = df1['Binary'].fillna(0)
df1 = df1.fillna(0)
#df1['multi_class'] = df1['multi_class'].fillna(0)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [73]:
df1.head()

Unnamed: 0  Unnamed: 0.1  ...            Asset  Binary
0           0             0  ...  Ashland_Unit256     0.0
1           1             1  ...  Ashland_Unit256     0.0
2           2             2  ...  Ashland_Unit256     0.0
3           3             3  ...  Ashland_Unit256     0.0
4           4             4  ...  Ashland_Unit256     0.0

[5 rows x 16 columns]

In [74]:
df1.shape

(124842, 16)

In [75]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'time', 'cyl', 's_temp_crank',
       'd_temp_crank', 's_pressure_crank', 'd_pressure_crank', 'rpm_crank',
       's_temp_mean', 'd_temp_mean', 's_pressure_mean', 'd_pressure_mean',
       'rpm_mean', 'Asset', 'Binary'],
      dtype='object')

In [76]:
X_columns = [ 'cyl', 's_temp_crank', 'd_temp_crank', 's_pressure_crank',\
       'd_pressure_crank', 'rpm_crank', 's_temp_mean', 'd_temp_mean',\
       's_pressure_mean', 'd_pressure_mean', 'rpm_mean']

In [77]:
len(X_columns)

11

In [78]:
X = df1[X_columns]

In [79]:
X.shape

(124842, 11)

# build  with mean

In [80]:
X

cyl  s_temp_crank  ...  d_pressure_mean     rpm_mean
0       1.0    103.113613  ...       820.900548  1357.932500
1       1.0     99.965045  ...       822.153967  1358.240000
2       1.0     98.503206  ...       829.080473  1398.281250
3       1.0    104.620153  ...       835.520144  1397.871250
4       1.0    109.567843  ...       838.433890  1397.310000
...     ...           ...  ...              ...          ...
138493  1.0     96.835182  ...        39.353878  1152.128750
138494  1.0     95.006198  ...        39.004776  1152.295000
138495  1.0     94.047816  ...        38.888198  1152.406875
138496  1.0     93.322582  ...        38.787718  1152.185000
138497  1.0     92.461638  ...        38.583256  1152.238750

[124842 rows x 11 columns]

In [81]:
y_true = df1.iloc[:,15]

In [82]:
y_true.unique()

array([0., 1.])

In [83]:
#seed = 42
test_size = 0.15
X_train, X_test, y_train, y_test = train_test_split(X, y_true, test_size=test_size,shuffle= True)

In [84]:
# X_val, X_test, y_val, y_test = train_test_split(X_Test, y_Test, test_size=0.75)

In [85]:
from collections import Counter

In [86]:
print(X_train.shape,y_train.shape)

(106115, 11) (106115,)


In [87]:
len(X_test)

18727

In [33]:
#len(X_val)

In [88]:
Counter(y_train)

Counter({0.0: 73179, 1.0: 32936})

64->16->4->1

In [89]:
class binaryClassification(nn.Module):
    def __init__(self):
        super(binaryClassification, self).__init__()
        # Number of input features is 11.
        self.layer_1 = nn.Linear(11, 64) 
        self.layer_2 = nn.Linear(64, 64)
        self.layer_3 = nn.Linear(64, 64)
        self.layer_4 = nn.Linear(64, 10)
        self.layer_5 = nn.Linear(10, 4)
        self.layer_out = nn.Linear(4, 1) 
        
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=0.1)
        self.batchnorm1 = nn.BatchNorm1d(64)
        self.batchnorm2 = nn.BatchNorm1d(64)
        self.batchnorm3 = nn.BatchNorm1d(64)
        self.batchnorm4 = nn.BatchNorm1d(10)

        
    def forward(self, inputs):
        x = self.relu(self.layer_1(inputs))
        x = self.batchnorm1(x)
        x = self.relu(self.layer_2(x))
        x = self.batchnorm2(x)
        x = self.relu(self.layer_3(x))
        x = self.batchnorm3(x)
        x = self.relu(self.layer_4(x))
        x = self.batchnorm4(x)
        x = self.relu(self.layer_5(x))
        x = self.dropout(x)
        x = self.layer_out(x)
        
        return x

In [90]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
#X_val = scaler.fit_transform(X_val)
X_test = scaler.fit_transform(X_test)

In [91]:
X_test

array([[-1.19492408,  0.33206065, -0.69527269, ...,  1.02432582,
         0.47888903,  0.27490141],
       [-0.25140916,  1.69077262,  1.396364  , ..., -0.71298618,
        -0.0531538 ,  0.6839079 ],
       [-1.19492408, -1.49768951, -0.11198699, ..., -0.26135794,
         0.44810608,  0.51473448],
       ...,
       [-0.25140916,  1.39758973,  1.40970769, ..., -0.68273908,
         0.11907178,  0.68318109],
       [ 1.63562067,  0.37462322,  0.01408412, ..., -1.02581729,
        -1.14428728, -1.41711287],
       [-1.19492408, -0.54158127, -0.48774594, ...,  0.30671641,
         0.36637245,  0.12747495]])

In [92]:
EPOCHS = 10
BATCH_SIZE = 75
LEARNING_RATE = 0.0792

In [93]:
## train data
class trainData(Dataset):
    
    def __init__(self, X_data, y_data):
        self.X_data = X_data
        self.y_data = y_data
        
    def __getitem__(self, index):
        return self.X_data[index], self.y_data[index]
        
    def __len__ (self):
        return len(self.X_data)

y_train = y_train.values
train_data = trainData(torch.FloatTensor(X_train),torch.FloatTensor(y_train))
## test data    
class testData(Dataset):
    
    def __init__(self, X_data):
        self.X_data = X_data
        
    def __getitem__(self, index):
        return self.X_data[index]
        
    def __len__ (self):
        return len(self.X_data)
# ## val data    
# class valData(Dataset):
    
#     def __init__(self, X_data):
#         self.X_data = X_data
        
#     def __getitem__(self, index):
#         return self.X_data[index]
        
#     def __len__ (self):
#         return len(self.X_data)

test_data = testData(torch.FloatTensor(X_test))
# val_data = valData(torch.FloatTensor(X_val))

In [94]:
train_loader = DataLoader(dataset=train_data, batch_size=BATCH_SIZE, shuffle=True)
# val_loader = DataLoader(dataset=val_data, batch_size=1)
test_loader = DataLoader(dataset=test_data, batch_size=1)

In [95]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [96]:
model = binaryClassification()
model.to(device)

binaryClassification(
  (layer_1): Linear(in_features=11, out_features=64, bias=True)
  (layer_2): Linear(in_features=64, out_features=64, bias=True)
  (layer_3): Linear(in_features=64, out_features=64, bias=True)
  (layer_4): Linear(in_features=64, out_features=10, bias=True)
  (layer_5): Linear(in_features=10, out_features=4, bias=True)
  (layer_out): Linear(in_features=4, out_features=1, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.1, inplace=False)
  (batchnorm1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (batchnorm2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (batchnorm3): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (batchnorm4): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)

In [97]:
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

In [98]:
def binary_acc(y_pred, y_test):
    y_pred_tag = torch.round(torch.sigmoid(y_pred))

    correct_results_sum = (y_pred_tag == y_test).sum().float()
    acc = correct_results_sum/y_test.shape[0]
    acc = torch.round(acc * 100)
    
    return acc

In [99]:
model.train()
for e in range(1, EPOCHS+1):
    epoch_loss = 0
    epoch_acc = 0
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        #X_batch = X_batch
  
        y_pred = model(X_batch)
        
        loss = criterion(y_pred, y_batch.unsqueeze(1))
        acc = binary_acc(y_pred, y_batch.unsqueeze(1))
        
        loss.backward()
        optimizer.step()
        
        epoch_loss += loss.item()
        epoch_acc += acc.item()

In [100]:
y_pred_list = []
model.eval()
with torch.no_grad():
    for X_batch in test_loader:
        X_batch = X_batch.to(device)
        y_test_pred = model(X_batch)
        y_test_pred = torch.sigmoid(y_test_pred)
        y_pred_tag = torch.round(y_test_pred)
        y_pred_list.append(y_pred_tag.cpu().numpy())

y_pred_list = [a.squeeze().tolist() for a in y_pred_list]

In [101]:
y_pred_list

[0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0

In [102]:
confusion_matrix(y_test, y_pred_list)

array([[11476,  1387],
       [ 1149,  4715]])

In [145]:
df2['Binary'] = df2['Binary'].fillna(0)
df2 = df1.fillna(0)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


# Old Assets

In [146]:
print(classification_report(y_test, y_pred_list))

ValueError: ignored

In [104]:
import pickle
filename = 'binarynn_dcp_model.pkl'

In [105]:
torch.save(model.state_dict(),filename)


In [106]:
model.load_state_dict(torch.load(filename))

<All keys matched successfully>

In [107]:
model.eval()

binaryClassification(
  (layer_1): Linear(in_features=11, out_features=64, bias=True)
  (layer_2): Linear(in_features=64, out_features=64, bias=True)
  (layer_3): Linear(in_features=64, out_features=64, bias=True)
  (layer_4): Linear(in_features=64, out_features=10, bias=True)
  (layer_5): Linear(in_features=10, out_features=4, bias=True)
  (layer_out): Linear(in_features=4, out_features=1, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.1, inplace=False)
  (batchnorm1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (batchnorm2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (batchnorm3): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (batchnorm4): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)

# Test Pred New Assets

In [147]:
X = df2[X_columns]

In [148]:
y_true = df2.iloc[:,15]

In [149]:
y_true.unique()

array([0., 1.])

In [150]:
X_test = scaler.fit_transform(X)

In [151]:
test_data = testData(torch.FloatTensor(X_test))

In [152]:
test_loader = DataLoader(dataset=test_data, batch_size=1)

In [153]:
X_test.shape

(124842, 11)

In [154]:
y_pred_list = []
with torch.no_grad():
    for X_batch in test_loader:
        X_batch = X_batch.to(device)
        y_test_pred = model(X_batch)
        y_test_pred = torch.sigmoid(y_test_pred)
        y_pred_tag = torch.round(y_test_pred)
        y_pred_list.append(y_pred_tag.cpu().numpy())



# New Assets

In [155]:
predictions=[]
predictions.append([y_pred_list[i][0][0] for i in range(len(y_pred_list))])

In [156]:
# predictions

In [157]:
len(y_true)

124842

In [158]:
len(predictions[0])

124842

In [159]:
predictions[0]

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [160]:
print(classification_report(y_true, predictions[0]))

              precision    recall  f1-score   support

         0.0       0.91      0.89      0.90     86042
         1.0       0.76      0.81      0.78     38800

    accuracy                           0.86    124842
   macro avg       0.84      0.85      0.84    124842
weighted avg       0.86      0.86      0.86    124842

