<a href="https://colab.research.google.com/github/theAkhileshRai/DeepLearning/blob/master/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import torch

In [45]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [46]:
scalar = torch.tensor(7, dtype=torch.float32)
scalar

tensor(7.)

In [47]:
scalar.ndim

0

In [48]:
scalar.item()

7.0

In [49]:
test= torch.tensor([7,7])
test

tensor([7, 7])

In [50]:
test.shape

torch.Size([2])

In [51]:
#MATRIX

MATRIX=torch.tensor([[2,4],[3,4]])

In [52]:
MATRIX.shape

torch.Size([2, 2])

In [53]:
#TENSOR

p = torch.tensor([[[1,3,2,4],
                  [3,2,4,5],
                  [4,3,2,4]]])

In [54]:
p.shape

torch.Size([1, 3, 4])

# Random Tensor

In [55]:
# Create a random tensor
Random_tensor = torch.rand(3,3,4)
Random_tensor

tensor([[[0.1707, 0.1149, 0.4621, 0.9689],
         [0.1028, 0.6495, 0.0045, 0.5812],
         [0.2042, 0.3247, 0.9581, 0.4508]],

        [[0.1573, 0.5999, 0.1542, 0.4639],
         [0.0479, 0.0740, 0.9195, 0.0881],
         [0.8794, 0.0494, 0.5477, 0.5887]],

        [[0.0064, 0.6679, 0.3403, 0.6246],
         [0.6130, 0.3915, 0.8883, 0.6729],
         [0.7720, 0.1829, 0.4187, 0.8362]]])

In [65]:
zeros_tensor= torch.zeros(3,3,4)
zeros_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [58]:
ones_tensor= torch.ones(3,3,4,dtype=int)
ones_tensor

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [64]:
torch.arange(end = 1,start = 10,step =-2)

tensor([10,  8,  6,  4,  2])

# Data Types tensor

Tensor data types one of the three big errors with pytorch and deep learning

[Datatypes](https://pytorch.org/docs/stable/tensors.html#data-types)



In [81]:
x = torch.tensor([[1,2,3]], requires_grad=True, dtype=torch.float32)
x

tensor([[1., 2., 3.]], requires_grad=True)

In [82]:
torch.mul(x,10)

tensor([[10., 20., 30.]], grad_fn=<MulBackward0>)

# Matrix Multiplication

As known in Math

In [83]:
x.shape

torch.Size([1, 3])

In [85]:
torch.matmul(x,x.T)

tensor([[14.]], grad_fn=<MmBackward0>)