<a href="https://colab.research.google.com/github/theAkhileshRai/DeepLearning/blob/master/Pytorch_Tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Pytorch object use Cuda

In [13]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [14]:
# check for GPU with Pytorch

import torch
torch.cuda.is_available()

False

In [15]:
# Device Agnostic code
device  = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [17]:
tensor1 = torch.tensor([1,23,34])
tensor1

tensor([ 1, 23, 34])

In [18]:
tensor_on_gpu = tensor1.to(device)
tensor_on_gpu

tensor([ 1, 23, 34])

In [20]:
## Numpy
tensor_on_gpu.cpu().numpy()

array([ 1, 23, 34])

## Exercises and Curriculum

In [21]:
torch.rand([7,7])

tensor([[0.0040, 0.7998, 0.3529, 0.1794, 0.1347, 0.3078, 0.1548],
        [0.6861, 0.5668, 0.3790, 0.8861, 0.8679, 0.3898, 0.3066],
        [0.1282, 0.5426, 0.0628, 0.7556, 0.5685, 0.5630, 0.8712],
        [0.4919, 0.3353, 0.8889, 0.8636, 0.5232, 0.6958, 0.1076],
        [0.4207, 0.6516, 0.5990, 0.0052, 0.3195, 0.1197, 0.2255],
        [0.0999, 0.6124, 0.6510, 0.6424, 0.5208, 0.9498, 0.9117],
        [0.9508, 0.5494, 0.5105, 0.7939, 0.4879, 0.6702, 0.0371]])

In [26]:
random_seed = 42
SEED = torch.manual_seed(random_seed)
a = torch.rand([7,7])
b = torch.rand([7,7])
torch.matmul(a,b)

tensor([[2.6637, 2.0426, 3.2242, 0.8659, 1.6420, 1.8317, 2.0220],
        [3.0324, 2.3639, 3.7553, 0.7506, 1.6955, 2.3543, 2.2479],
        [2.0545, 1.8111, 2.4874, 1.1800, 1.3461, 1.6582, 1.6263],
        [1.2061, 1.2405, 1.5288, 0.9969, 0.9076, 1.1420, 1.0550],
        [1.7111, 1.7710, 2.1770, 1.2673, 1.0596, 1.9356, 1.3243],
        [2.2473, 2.0134, 2.7834, 1.2568, 1.5264, 1.8804, 1.8302],
        [2.5960, 2.5335, 3.4685, 1.3261, 1.7587, 2.5078, 2.1685]])