<a href="https://colab.research.google.com/github/theAkhileshRai/DeepLearning/blob/master/TF_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##TF Basics

In [23]:
!pip install tensorflow==1.3

     |████████████████████████████████| 43.6MB 92kB/s 
     |████████████████████████████████| 1.6MB 44.4MB/s 
     |████████████████████████████████| 890kB 45.9MB/s 
  Created wheel for html5lib: filename=html5lib-0.9999999-cp36-none-any.whl size=107220 sha256=7641017b00b86d996fe169aaaf004199e626464015df5ce95f1dc1fdde22d131
  Stored in directory: /root/.cache/pip/wheels/50/ae/f9/d2b189788efcf61d1ee0e36045476735c838898eef1cad6e29
Successfully built html5lib
  Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Found existing installation: bleach 3.1.4
    Uninstalling bleach-3.1.4:
      Successfully uninstalled bleach-3.1.4
  Found existing installation: tensorflow 2.2.0rc3
    Uninstalling tensorflow-2.2.0rc3:
      Successfully uninstalled tensorflow-2.2.0rc3


In [24]:
import tensorflow as tf


/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:460: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:461: FutureWarning: Passing (type, 1) or 

In [0]:
hello = tf.constant("Hello")
world = tf.constant("World")

In [0]:
with tf.Session() as sess:
  result = sess.run(hello+world)

In [30]:
result

b'HelloWorld'

### Addition

In [31]:
a = tf.constant(10)
b = tf.constant(20)
with tf.Session() as sess:
  result = sess.run(a+b)

result

30

In [0]:
fill = tf.fill((10,10),10)
randomed = tf.random_normal((10,10))

In [0]:
myops = [fill,randomed]

In [0]:
sess = tf.InteractiveSession()

In [42]:
for op in myops:
  print(sess.run(op))
  print("\n")
  print("-"*100)
  print("\n")

[[10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]]


----------------------------------------------------------------------------------------------------


[[-1.0935637   0.10755637  1.7776148  -0.30940413 -0.7453005  -0.30955508
   0.68287104  0.52567255 -0.8246526  -0.95146775]
 [ 0.22827394 -0.13695326 -1.2137698   0.8561436   2.157627   -0.22439198
  -1.0717613  -0.9140779   0.28173363  0.2072558 ]
 [-1.33864    -0.10356988 -0.45240793  1.2536922  -0.18013877 -0.31719443
   0.88871235  0.6766872  -2.5774534   0.16570127]
 [-0.29313514 -0.36918604 -0.01393133  0.34796238 -0.63453174 -1.1659762
  -0.8903449   1.4884851   1.3885949   0.45095247]
 [-0.02309472  1.7616402   1.0136992  -1.1871959  -1.3844721  -0.

In [44]:
a = tf.constant([[1,2],[3,4]])
b= tf.constant([[1,2],[3,4]])
x = tf.matmul(a,b)
sess.run(x)

array([[ 7, 10],
       [15, 22]], dtype=int32)