<a href="https://colab.research.google.com/github/theAkhileshRai/DeepLearning/blob/master/TFClass_data_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==1.3.0

     |████████████████████████████████| 43.6MB 94kB/s 
     |████████████████████████████████| 1.6MB 17.4MB/s 
     |████████████████████████████████| 890kB 40.6MB/s 
  Created wheel for html5lib: filename=html5lib-0.9999999-cp36-none-any.whl size=107220 sha256=69c5096b450d258b8fedad4bfb0a15bdadd950e65371d9caa796892a5a75df58
  Stored in directory: /root/.cache/pip/wheels/50/ae/f9/d2b189788efcf61d1ee0e36045476735c838898eef1cad6e29
Successfully built html5lib
  Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Found existing installation: bleach 3.1.4
    Uninstalling bleach-3.1.4:
      Successfully uninstalled bleach-3.1.4
  Found existing installation: tensorflow 2.2.0rc3
    Uninstalling tensorflow-2.2.0rc3:
      Successfully uninstalled tensorflow-2.2.0rc3


In [2]:
import pandas as pd
import tensorflow as tf

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:460: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:461: FutureWarning: Passing (type, 1) or 

In [0]:
salary_census = pd.read_csv('/content/adult.csv')

In [4]:
salary_census.head()

age workclass  fnlwgt  ... hours.per.week  native.country income
0   90         ?   77053  ...             40   United-States  <=50K
1   82   Private  132870  ...             18   United-States  <=50K
2   66         ?  186061  ...             40   United-States  <=50K
3   54   Private  140359  ...             40   United-States  <=50K
4   41   Private  264663  ...             40   United-States  <=50K

[5 rows x 15 columns]

In [9]:
salary_census['occupation'].unique()

array(['?', 'Exec-managerial', 'Machine-op-inspct', 'Prof-specialty',
       'Other-service', 'Adm-clerical', 'Craft-repair',
       'Transport-moving', 'Handlers-cleaners', 'Sales',
       'Farming-fishing', 'Tech-support', 'Protective-serv',
       'Armed-Forces', 'Priv-house-serv'], dtype=object)

In [8]:
salary_census.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [0]:
cols_norm = 

In [0]:
salary_census=salary_census.drop(['workclass','occupation'],axis=1)

In [19]:
salary_census.head()

age  fnlwgt     education  ...  hours.per.week native.country income
0   90   77053       HS-grad  ...              40  United-States  <=50K
1   82  132870       HS-grad  ...              18  United-States  <=50K
2   66  186061  Some-college  ...              40  United-States  <=50K
3   54  140359       7th-8th  ...              40  United-States  <=50K
4   41  264663  Some-college  ...              40  United-States  <=50K

[5 rows x 13 columns]

In [21]:
salary_census['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [0]:
def label_fix(label):
  if label == '<=50K':
    return 0
  else:
    return 1

In [0]:
salary_census['income'] = salary_census['income'].apply(label_fix)

In [28]:
salary_census['income'].unique()

array([0, 1])

In [29]:
salary_census.head()

age  fnlwgt     education  ...  hours.per.week native.country income
0   90   77053       HS-grad  ...              40  United-States      0
1   82  132870       HS-grad  ...              18  United-States      0
2   66  186061  Some-college  ...              40  United-States      0
3   54  140359       7th-8th  ...              40  United-States      0
4   41  264663  Some-college  ...              40  United-States      0

[5 rows x 13 columns]

In [0]:
from sklearn.model_selection import train_test_split

x_data = salary_census.drop(['income'],axis =1)
y_data = salary_census['income']

In [31]:
x_data.head()

age  fnlwgt     education  ...  capital.loss hours.per.week native.country
0   90   77053       HS-grad  ...          4356             40  United-States
1   82  132870       HS-grad  ...          4356             18  United-States
2   66  186061  Some-college  ...          4356             40  United-States
3   54  140359       7th-8th  ...          3900             40  United-States
4   41  264663  Some-college  ...          3900             40  United-States

[5 rows x 12 columns]

In [33]:
y_data.unique()

array([0, 1])

In [0]:
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data,shuffle = True,test_size= 0.3, random_state=42)

In [36]:
salary_census.columns

Index(['age', 'fnlwgt', 'education', 'education.num', 'marital.status',
       'relationship', 'race', 'sex', 'capital.gain', 'capital.loss',
       'hours.per.week', 'native.country', 'income'],
      dtype='object')

In [0]:
sex = tf.feature_column.categorical_column_with_vocabulary_list('sex',['Female','Male'])

In [0]:
education = tf.feature_column.categorical_column_with_hash_bucket('education',hash_bucket_size=100)
marital_status = tf.feature_column.categorical_column_with_hash_bucket('marital.status',hash_bucket_size=100)
race = tf.feature_column.categorical_column_with_hash_bucket('race',hash_bucket_size=100)
native_country = tf.feature_column.categorical_column_with_hash_bucket('native.country',hash_bucket_size=100)
relationship = tf.feature_column.categorical_column_with_hash_bucket('relationship',hash_bucket_size=100)

In [0]:
age = tf.feature_column.numeric_column('age')
capital_loss = tf.feature_column.numeric_column('capital.loss')
capital_gain = tf.feature_column.numeric_column('capital.gain')
hours_per_week = tf.feature_column.numeric_column('hours.per.week')
education_num = tf.feature_column.numeric_column('education.num')
fnlwgt = tf.feature_column.numeric_column('fnlwgt')

In [0]:
feat_cols = [age, fnlwgt, education, education_num, marital_status,
       relationship, race, sex, capital_gain, capital_loss,
       hours_per_week, native_country]

In [0]:
input_func = tf.estimator.inputs.pandas_input_fn(x=x_train,y= y_train,batch_size=100,num_epochs=None,shuffle=True)

In [48]:
model = tf.estimator.LinearClassifier(feature_columns=feat_cols,n_classes=2)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpwfyf12os', '_tf_random_seed': 1, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100}


In [50]:
model.train(input_fn=input_func,steps=10000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Restoring parameters from /tmp/tmpwfyf12os/model.ckpt-1000
INFO:tensorflow:Saving checkpoints for 1001 into /tmp/tmpwfyf12os/model.ckpt.
INFO:tensorflow:loss = 34881.523, step = 1001
INFO:tensorflow:global_step/sec: 237.952
INFO:tensorflow:loss = 52838.867, step = 1101 (0.423 sec)
INFO:tensorflow:global_step/sec: 262.773
INFO:tensorflow:loss = 2382.0464, step = 1201 (0.379 sec)
INFO:tensorflow:global_step/sec: 258.76
INFO:tensorflow:loss = 5412.627, step = 1301 (0.386 sec)
INFO:tensorflow:global_step/sec: 266.807
INFO:tensorflow:loss = 43228.125, step = 1401 (0.375 sec)
INFO:tensorflow:global_step/sec: 263.871
INFO:tensorflow:loss = 15344.365, step = 1501 (0.379 sec)
INFO:tensorflow:global_step/sec: 258.745
INFO:tensorflow:loss = 3235.0688, step = 1601 (0.393 sec)
INFO:tensorflow:global_step/sec: 259.817
INFO:tensorflow:loss = 4027.827, step = 1701 (0.381 sec)
INFO:tensorflow:global_step/sec: 263.17
INFO:tensorflow:loss = 2783

In [0]:
my_pred_func = tf.estimator.inputs.pandas_input_fn(x=x_test,batch_size=len(x_test),shuffle=False)

In [0]:
pred_gen = model.predict(input_fn=my_pred_func)

In [62]:
predictions = list(pred_gen)

INFO:tensorflow:Restoring parameters from /tmp/tmpwfyf12os/model.ckpt-11000


In [63]:
predictions

[{'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'logistic': array([0.], dtype=float32),
  'logits': array([-864.52], dtype=float32),
  'probabilities': array([1., 0.], dtype=float32)},
 {'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'logistic': array([0.], dtype=float32),
  'logits': array([-1436.7058], dtype=float32),
  'probabilities': array([1., 0.], dtype=float32)},
 {'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'logistic': array([0.], dtype=float32),
  'logits': array([-633.1407], dtype=float32),
  'probabilities': array([1., 0.], dtype=float32)},
 {'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'logistic': array([0.], dtype=float32),
  'logits': array([-372.07343], dtype=float32),
  'probabilities': array([1., 0.], dtype=float32)},
 {'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'logistic': array([0.], dtype=float32),
  'logits': array([-208.11046], dtype=float32),
 

In [0]:
final_preds = [pred['class_ids'] for pred in predictions]

In [65]:
final_preds

[array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),

In [66]:
from sklearn.metrics import classification_report
classification_report(y_test,final_preds)

'              precision    recall  f1-score   support\n\n           0       0.78      1.00      0.87      7429\n           1       0.90      0.08      0.15      2340\n\n    accuracy                           0.78      9769\n   macro avg       0.84      0.54      0.51      9769\nweighted avg       0.81      0.78      0.70      9769\n'